### ISSUE TITLE
SSLCertVerificationError when following the tutorial

### ISSUE THREAD

**Issue by SmartDataCode** [microsoftgraph/msgraph-training-python#123]
Hi,

I cloned the repo and followed the [tutorial](https://learn.microsoft.com/en-us/graph/tutorials/python-app-only?tabs=aad), but keep getting the following error: 
`azure.core.exceptions.ServiceRequestError: Cannot connect to host login.microsoftonline.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)')]`
I'm running Python 3.10 on Macos, using a virtualenv. What am I doing wrong?

**Comment by jasonjoh** [comment]
Sounds like a Python environment issue. I found this which might help: https://stackoverflow.com/questions/75713846/ssl-certificate-verify-failed-certificate-verify-failed-unable-to-get-local-is

**Comment by SmartDataCode** [comment]
Works well! Thank you very much!
