### ISSUE TITLE
I cannot view the file attachments or body content

### ISSUE THREAD

**Issue by sglbl** [microsoftgraph/msgraph-training-python#183]
In the `main.py` file of user-auth, I cannot see the body or attachments:

The code that I've added to `list_inbox` function:
```python
            print('  Files:', message.has_attachments)
            print('  Body:', message.body.content)
            print('')
            # download attachments
            if message.has_attachments:
                attachments = await graph.get_attachments(message.id)
                for attachment in attachments:
                    print('Attachment:', attachment.name)
                    print('  Content:', attachment.content_bytes)
                    print('')
```

But I got:
`File "/home/sglbl/deduce/test/user-auth/graphtutorial/main.py", line 89, in list_inbox
    print('  Body:', message.body.content)
AttributeError: 'NoneType' object has no attribute **'content'`

When ı remove `message.body.content` line then I got:
```java
Message: Fwd: Roman Empire
  From: Sueleyman
  Status: Unread
  Received: 2024-10-30 10:18:22+00:00
  Files: None
```
But I'm sure attachments exist. Why cannot I see the attachments?

System:
```console
(.venv)antakya@hatay:~/test/user-auth/graphtutorial$ pip freeze | grep 'azure\|graph\|microsoft'
azure-core==1.31.0
azure-identity==1.19.0
cryptography==43.0.3
microsoft-kiota-abstractions==1.6.0
microsoft-kiota-authentication-azure==1.6.0
microsoft-kiota-http==1.6.0
microsoft-kiota-serialization-form==1.6.0
microsoft-kiota-serialization-json==1.6.0
microsoft-kiota-serialization-multipart==1.6.0
microsoft-kiota-serialization-text==1.6.0
msgraph-core==1.1.6
msgraph-sdk==1.11.0
```

**Comment by jasonjoh** [comment]
The code as written limits which properties come back for each message. Take a look at the `select` property in the `query_params`:

```python
query_params = MessagesRequestBuilder.MessagesRequestBuilderGetQueryParameters(
    # Only request specific properties
    select=['from', 'isRead', 'receivedDateTime', 'subject'],
    # Get at most 25 results
    top=25,
    # Sort by received time, newest first
    orderby=['receivedDateTime DESC']
)
```

You're going to want to add `body` and `has_attachments` to that array.

**Comment by sglbl** [comment]
> The code as written limits which properties come back for each message. Take a look at the `select` property in the `query_params`:
> 
> ```python
> query_params = MessagesRequestBuilder.MessagesRequestBuilderGetQueryParameters(
>     # Only request specific properties
>     select=['from', 'isRead', 'receivedDateTime', 'subject'],
>     # Get at most 25 results
>     top=25,
>     # Sort by received time, newest first
>     orderby=['receivedDateTime DESC']
> )
> ```
> 
> You're going to want to add `body` and `has_attachments` to that array.

Thank you, even though has_attachments doesn't work `attachments` do work.
