### ISSUE TITLE
broken with kiota-serializers-json 0.3.5

### ISSUE THREAD

**Issue by stbrie** [microsoftgraph/msgraph-training-python#74]
**Where did you get the code?**
- [ X] Downloaded from GitHub

**Describe the bug**
This is not a bug.  As the project is written, everything works fine. 

The requirements modules are out of date.   More recent versions are available for many.  Updating all to the latest versions, on python 3.10, I find that microsoft-kiota-serializers-json 0.3.5 breaks this project, while microsoft-kiota-serializers-json 0.3.4 works.

**To Reproduce**
1. in requirements.txt change:

   'microsoft-kiota-serializers-json==0.3.1'

to 

   'microsoft-kiota-serializers-json==0.3.5'

2. run: 

    python -m pip install -r requirements.txt
    python main.py

Workaround:

Don't microsoft-kiota-serializers-json past version 0.3.4

**Expected behavior**
Expect 
   Hello: (user)
   Email: (address)

Get
    Hello: None
    Email: None

**Desktop (please complete the following information):**
OS: Debian 11
Python 3.10

**Dependency versions**
 - msal: 1.22.0
 - msgraph-sdk: 1.0.0a12

**Additional context**
Not really a bug for this project, but don't know who to contact.

**Comment by jasonjoh** [comment]
@stbrie there's a new version of the SDK that incorporates the changes to the serialization library that's in the release process right now. Hopefully it will be available in the next few days. I'll keep this open to monitor.

**Comment by stbrie** [comment]
@jasonjoh You must have done something, because they kicked out a new version (0.3.6) of kiota-serializers-json that fixes the problem.

Please close this issue report.
