### ISSUE TITLE
TypeError: Can't instantiate abstract class GraphRequestAdapter with abstract method convert_to_native_async

### ISSUE THREAD

**Issue by edwardchenchen** [microsoftgraph/msgraph-training-python#87]
installing 
`msgraph-sdk`
now installs the 
`microsoft-kiota-abstractions==0.7.0`

it was not a problem with
`microsoft-kiota-abstractions==0.6.0`

going through issue
https://github.com/microsoftgraph/microsoft-graph-training/issues/164
I saw
this commit
https://github.com/microsoftgraph/msgraph-training-python/commit/6fe994e8f8dd4242c4881393d582d977487c0bbc
uses 
`microsoft-kiota-abstractions==0.6.0`

is there an updated use example for 0.7.0?

**Comment by jasonjoh** [comment]
This has been resolved.
